server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://192.168.33.10:3306/sequoia
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update